name: Pylodiversity
owner: ecology 
description: Tools to compute Phyloregions whith varaible model and clustering.
homepage_url: https://github.com/PaulineSGN/Workflow_Galaxy
long_description: |
  This tool suite proposes a workflow for phylodiversity analysis. The workflow aims to compute phylodiversity and endemism index to identify phyloregions based on count matrix and phylogenic tree. There are two big steps in this workflow : recuperation and normalisation of the data and computation of the phylodiversity and endemism index.
remote_repository_url: https://github.com/galaxyecology/tools-ecology/tree/master/tools/Phylodiversity_workflow
type: unrestricted
categories:
- Ecology
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Phylodiversity : {{ tool_name }}"
suite:
  name: "suite_phylodiversite"
  description: Tools to compute Phyloregions whith varaible model and clustering.
  long_description: |
    This tool suite proposes a workflow for phylodiversity analysis. The workflow aims to compute phylodiversity and endemism index to identify phyloregions based on count matrix and phylogenic tree. There are two big steps in this workflow : recuperation and normalisation of the data and computation of the phylodiversity and endemism index.