name: spocc_occ
owner: ecology
categories:
    -Ecology
description: Get species occurences data
homepage_url: https://cran.r-project.org/web/packages/spocc/index.html
long_description: |
    A programmatic interface to many species occurrence data sources, including Global Biodiversity Information Facility (GBIF), USGSs Biodiversity Information Serving Our Nation (BISON), iNaturalist, Berkeley Ecoinformatics Engine, AntWeb, Integrated Digitized Biocollections (iDigBio), VertNet, Ocean Biogeographic Information System (OBIS), and Atlas of Living Australia (ALA). 
    Includes functionality for retrieving species occurrence data, and combining those data.

remote_repository_url: https://github.com/galaxyecology/tools-ecology/tools/spocc_occ 
type: unrestricted 
