categories:
    - Ecology
description: Tools to compute and analyse biodiversity metrics
long_description: |
  Tools to compute and analyse biodiversity metrics derived from PAMPA scripts
name: pampa 
owner: ecology 
remote_repository_url: https://github.com/ColineRoyaux/PAMPA-Galaxy
type: unrestricted

repositories:
  pampa_presabs:
    description: Compute abundances and presence absence from raw count data
    owner: ecology
    include:
      - CalculatePresAbs.xml
      - pampa_macros.xml
      - FunctExeCalcPresAbsGalaxy.r
      - FunctPAMPAGalaxy.r
      - test-data/Observations.tabular
      
  pampa_communitymetrics:
    description: Compute community metrics from abundance data
    owner: ecology
    include:
      - CalculateCommunityMetrics.xml
      - pampa_macros.xml
      - FunctExeCalcCommIndexesGalaxy.r
      - FunctPAMPAGalaxy.r
      - test-data/Observations.tabular
      - test-data/TabMetricsFromSVRObs.tabular
      
  pampa_glmcomm:
    description: Compute GLM on community data
    owner: ecology
    include:
      - PAMPA_GLM.xml
      - pampa_macros.xml
      - FunctExeCalcGLMGalaxy.r
      - FunctPAMPAGalaxy.r
      - test-data/TabMetricsFromSVRObs.tabular
      - test-data/Unitobs.tabular
      
  pampa_glmsp:
    description: Compute GLM on population data
    owner: ecology
    include:
      - PAMPA_GLM_SP.xml
      - pampa_macros.xml
      - FunctExeCalcGLMSpGalaxy.r
      - FunctPAMPAGalaxy.r
      
