categories:
    - Ecology
owner: ecology
remote_repository_url: https://github.com/AquaINFRA/tools-ecology/tree/master
homepage_url: https://github.com/AquaINFRA/galaxy
long_description: |
  Wrapper for OGC API Processes developed in the AquaINFRA project.
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the OGC API Process: {{ tool_name }}."
