categories:
    - Ecology
owner: ecology
remote_repository_url: https://github.com/galaxyecology/tools-ecology/tree/master/tools/OtbBandMath
homepage_url: https://github.com/AquaINFRA/galaxy
long_description: |
  Outputs a monoband image which is the result of a mathematical operation on several multi-band images.
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the OGC API Process: {{ tool_name }}."
