categories:
    - ecology
owner: ecology
remote_repository_url: https://github.com/galaxyecology/tools-ecology/tree/master/tools/interpolation
homepage_url: https://github.com/AquaINFRA/galaxy
long_description: |
  This application smooths an image using the MeanShift algorithm.
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the OGC API Process: {{ tool_name }}."
