categories:
    - Ecology
owner: ecology
remote_repository_url: https://github.com/AquaINFRA/tools-ecology/tree/aquainfra_importer
homepage_url: https://github.com/AquaINFRA/galaxy
long_description: |
  A data source tool for downloading datasets via the AquaINFRA Interaction Platform.
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Data source tool for content provided in AquaINRA: {{ tool_name }}."
