categories:
    - Ecology
owner: ecology
remote_repository_url: https://github.com/galaxyecology/tools-ecology/tree/master/tools/ogc_api_processes_wrapper
homepage_url: https://github.com/AquaINFRA/galaxy
long_description: |
  This tool is a wrapper for OGC API Processes coming from the Zoo Project and was created using the OGC-API-Process2Galaxy tool (https://github.com/AquaINFRA/OGC-API-Process2Galaxy). Check the README in the repository for more information.
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for OGC API Processes: {{ tool_name }}."
