categories:
    - Ecology
owner: ecology
remote_repository_url: https://git.rwth-aachen.de/nfdi4earth/onestop4all/onestop4all-implementation/-/tree/develop
homepage_url: https://onestop4all.nfdi4earth.de/
long_description: |
  A data source tool for downloading datasets via NFDI4Earth's OneStop4All search user interface.
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Data source tool for content provided in NFDI4Earth's OneStop4All: {{ tool_name }}."
