name: Obitools4
owner: ecology 
description: Obitools4
homepage_url: https://github.com/kpayet26/tools-ecology
long_description: |
  Obitools4 are a set of tool for metabarcoding data. It allow the user to processing DNA metabarcoding data according to the biological questions. The idea behind the OBITools project was to provide a set of UNIX command-line tools that mimic standard UNIX shell commands such as grep, uniq or wc, but which work on DNA sequence files. Unlike standard UNIX tools, where the processing unit is a line of text, with OBITools the processing unit is a sequence record. In addition, some commands implementing algorithms specific to the processing of DNA metabarcoding data have been added, making OBITools one of the sequence processing tools widely used on UNIX-like systems, suitable for the analysis of DNA metabarcoding data. 
remote_repository_url: https://github.com/metabarcoding/obitools4
type: unrestricted
categories:
- Metabarcoding
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Obitools4: {{ tool_name }}"
suite:
  name: "suite_obitools4"
  description: Tools to processing DNA metabarcoding data.
  long_description: |
    Obitools4 are a set of tool for metabarcoding data. It allow the user to processing DNA metabarcoding data according to the biological questions. The idea behind the OBITools project was to provide a set of UNIX command-line tools that mimic standard UNIX shell commands such as grep, uniq or wc, but which work on DNA sequence files. Unlike standard UNIX tools, where the processing unit is a line of text, with OBITools the processing unit is a sequence record. In addition, some commands implementing algorithms specific to the processing of DNA metabarcoding data have been added, making OBITools one of the sequence processing tools widely used on UNIX-like systems, suitable for the analysis of DNA metabarcoding data.
