categories:
    - Ecology
owner: ecology
remote_repository_url: https://github.com/galaxyecology/tools-ecology/tree/master/tools/data_manipulation/xarray/
homepage_url: http://xarray.pydata.org
long_description: |
  xarray (formerly xray) is an open source project and Python package that makes working with
  labelled multi-dimensional arrays simple, efficient, and fun!
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for xarray tool: {{ tool_name }}."
suite:
  name: "suite_xarray"
  description: "A suite of xarray tools"
  type: repository_suite_definition

