categories:
    - Ecology
owner: ecology
remote_repository_url: https://github.com/galaxyecology/tools-ecology/tree/master/tools/ocean_data_view_manager
homepage_url: https://github.com/Marie59/FE-ft-ESG/tree/main/ocean
long_description: |
  The tool merges various datasets with a common vocabulary and creates a single generic ODV spreadsheet in an automatic way.
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for ocean biogechemical data tool: {{ tool_name }}."
