categories:
    - Ecology
owner: ecology
remote_repository_url: https://github.com/galaxyecology/tools-ecology/tree/master/tools/earth
homepage_url: https://github.com/Marie59/FE-ft-ESG/tree/main/earth
long_description: |
  Access, process, visualise oceanographic data for the Earth System
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for earth data tool: {{ tool_name }}."
suite:
  name: "earth_suite"
  description: "A suite of tools for the earth compartment of the Earth System"
  type: unrestricted
