name: Retrieve Bold 
owner: ecology 
description: Search a list of sequences in BOLD (Barcode of Life Data System) from specified taxa list and markers
homepage_url: https://anaconda.org/conda-forge/r-bold
long_description: |
This tool was created from the MARES Database pipeline repository. Sequences are retrieved thanks to BOLD r-package (Barcode of Life Data System). This tool provides a fasta file for each to be processed taxa. This tool allows the specification of a wide diversity of metabarcoding markers. 
remote_repository_url: https://github.com/wpearman1996/MARES_database_pipeline/tree/master
type: unrestricted
categories:
- Ecology
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Search a list of sequences from BOLD"
