name: PyloIndex
owner: ecology 
description: Tools to computes the phylodiversity index.
homepage_url: https://github.com/Morphy427/phylodiversity_workflow/PyloIndex
long_description: |
  This tool computes the phylodiversity index based on matched phylogenetic and occupancy data.
remote_repository_url: https://github.com/galaxyecology/tools-ecology/tree/master/tools/Phylodiversity_workflow
type: unrestricted
categories:
- Ecology
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Phylodiversity : {{ tool_name }}"
