name: MetaShRIMPS 
owner: ecology 
description: Tools to operate machine actionnable actions on EML metadata
homepage_url: https://github.com/tanguygen/metacure
long_description: |
    Tools to operate machine actionnable jobs to EML metadata from MetaShRIMPS, a project from the PNDB (French hub for biodiversity data)
remote_repository_url: https://github.com/galaxyecology/tools-ecology/tree/master/tools/EMLassemblyline
type: unrestricted
categories:
- Ecology
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "MetaShRIMPS: {{ tool_name }}"
suite:
  name: "suite_metashrimps"
  description: Tools to operate machine actionnable jobs on EML metadata
  long_description: |
    Tools to operate machine actionnable jobs to EML metadata from MetaShRIMPS, a project from the PNDB (French hub for biodiversity data).
