categories:
    - Ecology 
description: Tools created by the vigiechiro team to analyses and identify chiro sounds files.
long_description: |
  The Vigie Chiro is a french scientific citizen program that studies bats. This tools suite allows to analyse data from the vigiechiro.herokuapp.com web portal and to create advanced restitutions. Two tools are useful to clean and synthetize data according to the sampling session. The other two produce advanced restitution based on the protocol used.

homepage_url: https://www.vigienature-ecole.fr/les-observatoires/le-protocole-vigie-chiro 
name: vigiechiro
owner: ecology 
remote_repository_url: https://github.com/galaxyecology/tools-ecology/tree/master/tools/vigiechiro
type: unrestricted


repositories:
  vigiechiro_bilanenrichipf:
    description: "'Point fixe' protocol advanced restitution tool from the vigiechiro suite"
    owner: ecology
    include:
      - vigiechiro_macros.xml  
      - BilanEnrichiPFen.xml    
      - BilanEnrichiPF.R  
      - refPF.csv
      - SpeciesList.csv
      - test-data/BilanEnrichiPF_Test1_out_tab.tabular
      - test-data/BilanEnrichiPF_Test1.tabular  
      - test-data/BilanEnrichiPF_Test1_hourly.tabular  
      - test-data/BilanEnrichiPF_Test1_nightly.tabular

  vigiechiro_bilanenrichirp:  
     description: "'Routier' or 'Pedestre' protocols advanced restitution tool from the vigiechiro suite"
     owner: ecology
     include:        
      - vigiechiro_macros.xml  
      - BilanEnrichiRPen.xml    
      - BilanEnrichiRP.R  
      - refRPSeuil50.csv
      - SpeciesList.csv
      - test-data/BilanEnrichiRP_Test1_out_tab.tabular
      - test-data/BilanEnrichiRP_Test1_summarised.tabular 
      - test-data/BilanEnrichiRP_Test1.tabular 

  vigiechiro_idcorrect_2ndlayer: 
    description: "Tadarida data clean tool from the vigiechiro suite"
    owner: ecology
    include:        
      - vigiechiro_macros.xml  
      - IdTidyen.xml
      - Id_Tidy.R
      - test-data/input_tidy_test1_obs.csv
      - test-data/output_tidy.tabular 


  vigiechiro_idvalid:
    description: "Tadarida identifications integration tool from the vigiechiro suite"    
    owner: ecology
    include:    
      - vigiechiro_macros.xml  
      - IdValidTidy.R
      - IdValidTidyen.xml
      - test-data/output_tidy.tabular 
      - test-data/IdValidTidy.tabular  
